# Generated by Django 6.1.1 on 2026-09-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_friendship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['username'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
