# Generated by Django 6.1.1 on 2026-09-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('direct', 'direct'), ('channels', 'channels')], default='direct', max_length=200),
        ),
    ]
