# Generated by Django 6.1.1 on 2026-10-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
