# Generated by Django 6.1.1 on 2026-10-03 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_conversation_name"),
        ("core", "0003_alter_profile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_channels",
                to="core.profile",
            ),
        ),
    ]
